
library(dplyr)
library(lubridate)
library(runjags)
library(parallel)
library(coda)

# Get species richness at sites and calculate correlations

model <- "./JAGS/multi_scale_occupancy_simpler_RE.R"
min_dets <- 19
include_inxs <- FALSE
# Whether or not you want to check out the gelman rubin diagnostic
#  of parameters
check_grdiag <- FALSE
# my_species <- c(
#   "armadillo",
#   "cottontail_sp",
#   "coyote",
#   "eastern_chipmunk",
#   "flying_squirrel_sp",
#   "gray_fox",
#   "gray_squirrel_sp",
#   "raccoon",
#   "red_fox",
#   "red_squirrel",
#   "striped_skunk",
#   "virginia_opossum",
#   "white_tailed_deer",
#   "woodchuck")
source("./R/prep_data_for_model.R")
# bring in the model output

m1 <- readRDS("./results/final_model_fit.RDS")


# The really big item we need from that sourced file is the 'tmp' object.
#  It connects our sampled data to sites, seasons, cities, etc.
mc <- as.matrix(
  as.mcmc.list(m1),
  chains = TRUE
)[,-1]

rm(m1)

# split off the x stuff (whether a species is actually in a city)
mx <- mc[, grep("^x\\[", colnames(mc))]

mc <- mc[,-grep("^x\\[", colnames(mc))]


# collect the species level coefficients
b_species_city <- mc[,grep("^b_species_city", colnames(mc))]

# we are only going to do this with a subset of the posterior,
#  or else it's going to be too much of a computational load
#  on my computer.

set.seed(3122020)
to_collect <- sample(1:nrow(mc), 9000)

samp <- b_species_city[to_collect,]

sampx <- mx[to_collect,] 

rm(mc)
rm(mx)
# pull some of the counts and id variables from the data_list,
#  which was generated by the sourced file above.'
# also make a siteidx from tmp
ncov_within <- data_list$ncov_within
species_idx <- data_list$species_idx
city_idx <- data_list$city_idx
site_idx <- as.numeric(
  factor(
    tmp$Site,
    levels = unique(tmp$Site)
  )
)

# set up in an array similar to what we have in our jags model.
b_species_city <- array(
  samp, 
  dim = c(
    length(to_collect),
    ncov_within,
    data_list$nspecies,
    data_list$ncity
  )
)

# set up the species being present in a given locale
sampx_array <- array(
  sampx,
  dim = c(
    length(to_collect),
    data_list$nspecies,
    data_list$ncity
  )
)

z<- matrix(
  NA, 
  ncol = data_list$nsamples,
  nrow = length(to_collect)
)

# loop through the posterior samples and generate a detection corrected
#  estimate of a species occupancy

pb <- txtProgressBar(1, data_list$nsamples)
for(s in 1:data_list$nsamples){
  setTxtProgressBar(pb, s)  
  # if we detected the species there we don't need to do the rest
  if(data_list$y[s] > 0){
    z[,s] <- 1 
    next
  }
  # calculate average log-odds per site
  l_psi <- 
    b_species_city[,,species_idx[s],
                   city_idx[s]
    ] %*% data_list$psi_covs[s,]
  # convert to probability
  psi <- plogis(l_psi)
  # generate whether species was present or not
    z[,s] <- rbinom(length(to_collect), 1, psi) * 
      sampx_array[,species_idx[s], city_idx[s]]
}

rm(psi)
rm(l_psi)
rm(sampx_array)
rm(samp)
rm(sampx)

# Get median community matrix for each city
z_med <- rep(NA, ncol(z))
pb <- txtProgressBar(max = length(z_med))
for(i in 1:length(z_med)){
  setTxtProgressBar(pb,i)
  z_med[i] <- median(z[,i])
}

z_med[z_med>0] <- 1

# get combo of site, city, and season. This will let us calculate
#  species richness by site, city, and season
unid <- paste(tmp$Site, tmp$City, tmp$Season, sep = "_")
un <- as.numeric(factor(unid, levels = unique(unid)))

my_rich <- data.frame(
  med = NA,
  lo = NA,
  hi = NA,
  Site = tmp$Site,
  City = tmp$City,
  Season = tmp$Season
)



# tack on income as well
# drop duplicates
to_go <- which(duplicated(my_rich))
my_rich <- my_rich[-to_go,]

my_rich_id <- as.numeric(
  factor(my_rich$City, levels = city_map$City)
)

rich_mcmc <- matrix(
  ncol = nrow(my_rich),
  nrow = length(to_collect)
)
z_mat <- matrix(NA, ncol = nrow(species_map), nrow = nrow(my_rich))

for(i in 1:nrow(my_rich)){
  rich_mcmc[,i] <- rowSums(z[, which(un == i)])
  z_mat[i,] <- z_med[which(un == i)]
  my_rich[i, 1:3] <- quantile(rich_mcmc[,i], probs = c(0.5,0.025,0.975)) 
}

colnames(z_mat) <- species_map$Species

# Do correlation of species richness to income and urb for each city
income_cor <- urb_cor <-  matrix(
  ncol = data_list$ncity,
  nrow = length(to_collect)
)

psi_cov_cor <- data_list$psi_covs[-to_go,]

pb <- txtProgressBar(1, nrow(income_cor))
for(i in 1:nrow(income_cor)){
  setTxtProgressBar(pb, i)  
  for(j in 1:data_list$ncity){
    in_city <- which(my_rich_id == j)
  income_cor[i,j] <- cor(
    rich_mcmc[i,in_city],
    data_list$psi_covs[in_city,2]
  )
  urb_cor[i,j] <- cor(
    rich_mcmc[i,in_city],
    data_list$psi_covs[in_city,3]
  )
  }
  }

# get quantiles
urb_quants <- t(
  apply(
    urb_cor, 2, quantile, probs = c(0.025,0.5,0.975)
  )
)
row.names(urb_quants) <- city_map$City
colnames(urb_cor) <- city_map$City

urb_quants <- round(urb_quants, 2)

urb_quants[order(urb_quants[,2], decreasing = TRUE),] 


income_quants <- t(
  apply(
    income_cor, 2, quantile, probs = c(0.025,0.5,0.975)
  )
)
row.names(income_quants) <- city_map$City
colnames(income_cor) <- city_map$City
income_quants <- round(income_quants, 2)

income_quants[order(income_quants[,2], decreasing = TRUE),] 

#windows(8,8)
#par(mar = c(0,0,0,0))


# 
# colfunc <- colorRampPalette(c("blue", "white", "red"))
# my_cols <- colfunc(21)
# 
# test <- cut(hm, breaks = seq(-1,1, 0.1))
# 
# hm <- income_quants[,2]
# 
# hm_col <- my_cols[as.numeric()]

# map("worldHires", c("Canada", "USA"),  xlim=c(-170,-53), ylim = c( 20, 85))
# points(city_ll[,c(2,1)], pch = 21, bg = hm_col, cex = 2)
# 
# test <- map_data
# 
# plot(c(1:nrow(income_quants)) ~ income_quants[,2])
# 
# income_samples <- left_join(
#   tmp[,c("Site","City",  "Season")],
#   within_covs[,c("Site", "City", "Season", "Income")],
#   by = c("Site", "Season", "City")
# )

within_covs$URB <- cov_pca$x[,1]
nm_cat <- inner_join(
  my_rich,
  within_covs[,c("Site", "City", "Season", "Income", "URB")],
  by = c("Site", "Season", "City")
  )

nm_mean <- nm_cat %>% 
  group_by(Site, City) %>% 
  summarise(Income = mean(Income),
            URB = mean(URB))


my_rich <- my_rich %>% group_by(Site, City) %>% 
  summarise(med = mean(med),
            lo = mean(lo),
            hi = mean(hi))

# You can use this to get a look at species richness at the
#  most and least urban sites
c_lo <- nm_mean %>% 
  dplyr::filter(City == 'phaz') %>% 
  dplyr::arrange(URB) %>% 
  head(5)

c_hi <- nm_mean %>% 
  dplyr::filter(City == 'phaz') %>% 
  dplyr::arrange(URB) %>% 
  tail(5)


quantile(
  rowMeans(rich_mcmc[, which(nm_cat$Site %in% c_lo$Site)]),
  probs = c(0.025,0.5,0.975)
)


quantile(
  rowMeans(rich_mcmc[, which(nm_cat$Site %in% c_hi$Site)]),
  probs = c(0.025,0.5,0.975)
)

mu_covs <- within_covs[,c("Site", "City", "Income", "URB")] %>% 
  group_by(Site,City) %>% 
   summarise(Income = mean(Income),
             URB = mean(URB))

my_rich <- inner_join(my_rich, mu_covs, by = c("Site", "City") )
plot_lim <- c(0, max(my_rich$hi) + 1)
my_rich <- split(my_rich, factor(my_rich$City))

x_lim_inc <- c(0,250)
x_lim_urb <- c(
  -4,4
)

my_rich_income <- my_rich[order(income_quants[,2], decreasing = TRUE)]

my_rich_urb <- my_rich[order(urb_quants[,2])]
inc_ord <- income_quants[order(income_quants[,2], decreasing = TRUE),]
urb_ord <- urb_quants[order(urb_quants[,2]),]
# 
# pdf("income_richness_all_species.pdf", height = 6, width = 6)
# for(i in 1:length(my_rich)){
#   tp <- my_rich_income[[i]]
#   
#   plot(tp$med ~ tp$Income, 
#        ylim = plot_lim, 
#        xlim = x_lim_inc,
#        xlab = "Median income within 1 km of site",
#        ylab = "species richness",
#        bty = 'l',
#        las = 1,
#        main = unique(tp$City),
#        pch = 19,
#        cex = 1.2)
#   for(j in 1:nrow(tp)){
#     lines(x = rep(tp$Income[j], 2),
#           y = c(tp$lo[j], tp$hi[j]))
#   }
#   u <- par("usr")
#   text(x = u[1] * 1.2, y = u[4] -0.5,
#        labels = 
#          paste0(
#            "Pearson's r = ",
#            inc_ord[i,2],
#            " (95% BCI = ",
#            inc_ord[i,1],
#            " - ",
#            inc_ord[i,3],
#            ")"
#            ),
#        pos = 4
#   )
# }
# dev.off()
# 
# 
# 
# pdf("URB_richness_all_species.pdf", height = 6, width = 6)
# for(i in 1:length(my_rich_urb)){
#   tp <- my_rich_urb[[i]]
#   
#   plot(tp$med ~ tp$URB, 
#        ylim = plot_lim, 
#        xlim = x_lim_urb,
#        xlab = "URB PCA",
#        ylab = "species richness",
#        bty = 'l',
#        las = 1,
#        main = unique(tp$City),
#        pch = 19,
#        cex = 1.2)
#   for(j in 1:nrow(tp)){
#     lines(x = rep(tp$URB[j], 2),
#           y = c(tp$lo[j], tp$hi[j]))
#   }
#   u <- par("usr")
#   text(x = u[1] +0.5, y = u[4] -0.5,
#        labels = 
#          paste0(
#            "Pearson's r = ",
#            urb_ord[i,2],
#            " (95% BCI = ",
#            urb_ord[i,1],
#            " - ",
#            urb_ord[i,3],
#            ")"
#          ),
#        pos = 4
#   )
# }
# dev.off()

